// Generated by CoffeeScript 1.4.0
var app, port, server;

app = require('./.app');

port = app.port;
server = app.server;

server.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
